version: "3.3"

networks:
  # docker internal network
  lempnet:
    driver: bridge

services:

  # LEMP Server from image
  app:
    image: lemp-dev:v2
    container_name: drupalwebapp    
    env_file:
      - .env
    working_dir: /var/www/html/
    ports:
        - 80:80    
        - 443:443
        - 3306:3306        
    volumes:
      - ../www:/var/www/html/
#      - ./setup:/setup/
    networks:
      - lempnet          
    tty: true